---
site_name: AIDA Data Hub Documentation
theme:
  name: material
  logo: imgs/logos/aida-icon-logo.png
  favicon: imgs/logos/AIDA-icon-6.png
  features:
    - content.code.copy
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
extra:
  social:
    - icon: fontawesome/brands/github
extra_css:
  - style.css
repo_url: https://github.com/NBISweden/aida-datahub-docs/
repo_name: NBISweden/aida-datahub-docs

plugins:
  - search
  - awesome-nav

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
